"""boolean_default

Revision ID: 978129bf15fe
Revises: dfefdac3d90c
Create Date: 2021-03-04 15:29:30.427535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '978129bf15fe'
down_revision = 'dfefdac3d90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('samplers', 'private',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('samplers', 'private',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
