"""empty message

Revision ID: c8f73997bec8
Revises: a920b9e255ec
Create Date: 2021-03-05 17:31:57.554368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f73997bec8'
down_revision = 'a920b9e255ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samplers', sa.Column('priv', sa.Boolean(), nullable=False))
    op.drop_column('samplers', 'private')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samplers', sa.Column('private', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('samplers', 'priv')
    # ### end Alembic commands ###
