"""empty message

Revision ID: 56ceb6434b7e
Revises: ffdc0a98111c
Create Date: 2021-03-04 15:17:18.410683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ceb6434b7e'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samplers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('sampleOne', sa.String(), nullable=True),
    sa.Column('sampleTwo', sa.String(), nullable=True),
    sa.Column('sampleThree', sa.String(), nullable=True),
    sa.Column('sampleFour', sa.String(), nullable=True),
    sa.Column('sampleFive', sa.String(), nullable=True),
    sa.Column('sampleSix', sa.String(), nullable=True),
    sa.Column('sampleSeven', sa.String(), nullable=True),
    sa.Column('sampleEight', sa.String(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('samplers')
    # ### end Alembic commands ###
