"""created_at_column_add

Revision ID: dfefdac3d90c
Revises: 56ceb6434b7e
Create Date: 2021-03-04 15:22:43.411275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfefdac3d90c'
down_revision = '56ceb6434b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samplers', sa.Column('createdAt', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samplers', 'createdAt')
    # ### end Alembic commands ###
