"""empty message

Revision ID: a920b9e255ec
Revises: 978129bf15fe
Create Date: 2021-03-05 13:53:26.714738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a920b9e255ec'
down_revision = '978129bf15fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samplers', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samplers', 'title')
    # ### end Alembic commands ###
